import {
  BookOpen,
  Cloud,
  Film,
  Gamepad2,
  Music,
  Shield,
  Video,
  Wifi,
} from 'lucide-react-native';

export const HOME_USER = {
  name: 'Ocha Oxana',
};

export const HOME_BALANCE = {
  amount: 10000000,
  nextRenewalDate: '2026-03-30T09:00:00.000Z',
};

export const UPCOMING_SUBSCRIPTION = [
  {
    id: 'spotify',
    icon: Music,
    name: 'Spotify',
    price: 68000,
    currency: 'IDR',
    daysLeft: 4,
  },
  {
    id: 'netflix',
    icon: Film,
    name: 'Netflix',
    price: 186000,
    currency: 'IDR',
    daysLeft: 2,
  },
  {
    id: 'youtube_premium',
    icon: Video,
    name: 'YouTube Premium',
    price: 99000,
    currency: 'IDR',
    daysLeft: 7,
  },
  {
    id: 'apple_music',
    icon: Music,
    name: 'Apple Music',
    price: 55000,
    currency: 'IDR',
    daysLeft: 10,
  },
  {
    id: 'google_drive',
    icon: Cloud,
    name: 'Google One (Drive)',
    price: 26900,
    currency: 'IDR',
    daysLeft: 1,
  },
  {
    id: 'playstation_plus',
    icon: Gamepad2,
    name: 'PlayStation Plus',
    price: 89000,
    currency: 'IDR',
    daysLeft: 14,
  },
  {
    id: 'kindle_unlimited',
    icon: BookOpen,
    name: 'Kindle Unlimited',
    price: 149000,
    currency: 'IDR',
    daysLeft: 5,
  },
];

export const HOME_SUBSCRIPTION: Subscription[] = [
  {
    id: 'spotify_family',
    icon: Music,
    name: 'Spotify',
    plan: 'Family',
    category: 'Entertainment',
    paymentMethod: 'Visa •••• 1123',
    status: 'active',
    startDate: '2025-06-12',
    price: 86000,
    currency: 'IDR',
    billing: 'monthly',
    renewalDate: '2026-04-04',
    color: '#1DB954',
  },
  {
    id: 'netflix_premium',
    icon: Film,
    name: 'Netflix',
    plan: 'Premium',
    category: 'Entertainment',
    paymentMethod: 'GoPay',
    status: 'active',
    startDate: '2024-11-01',
    price: 186000,
    currency: 'IDR',
    billing: 'monthly',
    renewalDate: '2026-04-02',
    color: '#E50914',
  },
  {
    id: 'youtube_premium',
    icon: Video,
    name: 'YouTube Premium',
    plan: 'Individual',
    category: 'Entertainment',
    paymentMethod: 'OVO',
    status: 'active',
    startDate: '2025-01-20',
    price: 99000,
    currency: 'IDR',
    billing: 'monthly',
    renewalDate: '2026-04-07',
    color: '#FF0000',
  },
  {
    id: 'google_one',
    icon: Cloud,
    name: 'Google One',
    plan: '200GB',
    category: 'Cloud Storage',
    paymentMethod: 'Mastercard •••• 8891',
    status: 'active',
    startDate: '2025-03-15',
    price: 26900,
    currency: 'IDR',
    billing: 'monthly',
    renewalDate: '2026-04-01',
    color: '#4285F4',
  },
  {
    id: 'ps_plus_extra',
    icon: Gamepad2,
    name: 'PlayStation Plus',
    plan: 'Extra',
    category: 'Gaming',
    paymentMethod: 'Visa •••• 7782',
    status: 'active',
    startDate: '2024-09-10',
    price: 890000,
    currency: 'IDR',
    billing: 'yearly',
    renewalDate: '2026-09-10',
    color: '#F5D849',
  },
  {
    id: 'kindle_unlimited',
    icon: BookOpen,
    name: 'Kindle Unlimited',
    plan: 'Standard',
    category: 'Reading',
    paymentMethod: 'Dana',
    status: 'paused',
    startDate: '2025-02-05',
    price: 149000,
    currency: 'IDR',
    billing: 'monthly',
    renewalDate: '2026-04-05',
    color: '#FBF0D9',
  },
  {
    id: 'home_wifi',
    icon: Wifi,
    name: 'IndiHome',
    plan: '100 Mbps',
    category: 'Utilities',
    paymentMethod: 'Bank Transfer (BCA)',
    status: 'active',
    startDate: '2023-08-01',
    price: 375000,
    currency: 'IDR',
    billing: 'monthly',
    renewalDate: '2026-04-03',
    color: '#EC1E47',
  },
  {
    id: 'nordvpn',
    icon: Shield,
    name: 'NordVPN',
    plan: '2-Year Plan',
    category: 'Security',
    paymentMethod: 'PayPal',
    status: 'expired',
    startDate: '2023-03-28',
    price: 1200000,
    currency: 'IDR',
    billing: 'yearly',
    renewalDate: '2025-03-28',
    color: '#3E5FFF',
  },
];
